/**
 * @module EdlExporter
 * Exports a VideoForge Project to CMX3600 EDL (Edit Decision List) format.
 *
 * Pipeline:
 *   Project → TimelineConverter → IntermediateTimeline → EdlExporter → .edl file
 *
 * CMX3600 EDL format:
 *   - One edit event per clip (video cuts only; dissolves are supported).
 *   - Format: <event#> <reel> <channels> <edit_type> <src_in> <src_out> <rec_in> <rec_out>
 *   - Audio-only clips are omitted from primary events but appended as AX events.
 *   - Transitions become dissolve events.
 *   - SMPTE NDF timecodes unless project fps is 29.97 or 59.94 (DF).
 *
 * Limitations (documented in output header):
 *   - Effects, captions, transforms, and opacity are not representable.
 *     These are preserved in the comment block at the top of the file.
 *   - Only the primary video track is exported as the main event list.
 *   - Secondary video tracks are annotated as comments.
 */

import { promises as fs } from 'fs';
import path from 'path';
import Exporter from './Exporter.js';
import TimelineConverter    from '../interchange/TimelineConverter.js';
import InterchangeValidator from '../interchange/validation/InterchangeValidator.js';
import XmlValidator         from '../interchange/utils/XmlValidator.js';
import TimeCode             from '../interchange/utils/TimeCode.js';

class EdlExporter extends Exporter {
  /**
   * @param {import('../core/Project.js').default} project
   * @param {object} [options={}]
   * @param {string}  [options.title]              - EDL title (defaults to project name).
   * @param {boolean} [options.dropFrame]          - Force DF timecode. Defaults to auto (true for 29.97/59.94).
   * @param {boolean} [options.includeAudio=true]  - Include audio-only AX events.
   * @param {boolean} [options.includeComments=true] - Emit comment lines for unsupported features.
   * @param {boolean} [options.validateInput=true]
   */
  constructor(project, options = {}) {
    super(project, options);
    this.title           = options.title           ?? null;
    this.dropFrame       = options.dropFrame       ?? null; // null = auto
    this.includeAudio    = options.includeAudio    ?? true;
    this.includeComments = options.includeComments ?? true;
    this._converter      = new TimelineConverter();
    this._itrValidator   = new InterchangeValidator();
  }

  // ─── Exporter contract ────────────────────────────────────────────────────────

  async export(outputPath) {
    const dest = this.resolveOutputPath(outputPath, '.edl');
    await fs.mkdir(path.dirname(dest), { recursive: true });
    const edl = this.toString();
    await fs.writeFile(dest, edl, 'utf8');
    return dest;
  }

  /**
   * Generate and return the CMX3600 EDL string without writing to disk.
   * @returns {string}
   */
  toString() {
    const itr = this._converter.convert(this.project);

    if (this.validateInput ?? true) {
      const result = this._itrValidator.validateTimeline(itr);
      if (!result.valid) {
        throw new Error(
          `EdlExporter: ITR validation failed:\n${result.errors.join('\n')}`,
        );
      }
    }

    return this._buildEdl(itr);
  }

  // ─── EDL document ─────────────────────────────────────────────────────────────

  _buildEdl(itr) {
    const fps = itr.fps;
    const isNtsc = TimeCode.premiereRate(fps).ntsc;
    const useDropFrame = this.dropFrame ?? isNtsc;

    const lines = [];

    // Header
    lines.push(`TITLE: ${this.title ?? itr.name ?? 'Untitled'}`);
    lines.push(`FCM: ${useDropFrame ? 'DROP FRAME' : 'NON-DROP FRAME'}`);
    lines.push('');

    if (this.includeComments) {
      lines.push('* Generated by VideoForge EDL Exporter');
      lines.push(`* Project: ${itr.name}`);
      lines.push(`* FPS: ${fps}`);
      lines.push(`* Resolution: ${itr.width}x${itr.height}`);
      lines.push(`* Duration: ${this._tc(itr.duration, fps, useDropFrame)}`);
      lines.push('');
    }

    // Primary video track events
    const videoTracks = itr.getVideoTracks();
    let eventNum = 1;

    if (videoTracks.length === 0) {
      lines.push('* No video tracks found');
    } else {
      const primaryTrack = videoTracks[0];
      const clips = primaryTrack.getSortedClips();

      for (let i = 0; i < clips.length; i++) {
        const clip    = clips[i];
        const asset   = itr.getAsset(clip.assetId);
        const reelId  = this._reelId(asset, clip);
        const hasTrans = clip.transitions && clip.transitions.length > 0;

        // Dissolve event
        if (hasTrans && i > 0) {
          const trans    = clip.transitions[0];
          const durFrames = Math.round(trans.duration * fps);
          const prevClip  = clips[i - 1];
          const prevAsset = itr.getAsset(prevClip.assetId);

          lines.push(this._formatEvent(
            eventNum++,
            this._reelId(prevAsset, prevClip),
            'V',
            `D ${String(durFrames).padStart(3, '0')}`,
            this._tc(prevClip.sourceStart,       fps, useDropFrame),
            this._tc(prevClip.sourceEnd,         fps, useDropFrame),
            this._tc(prevClip.timelineStart,     fps, useDropFrame),
            this._tc(prevClip.timelineEnd,       fps, useDropFrame),
          ));

          lines.push(this._formatEvent(
            eventNum,
            reelId,
            'V',
            `D ${String(durFrames).padStart(3, '0')}`,
            this._tc(clip.sourceStart,   fps, useDropFrame),
            this._tc(clip.sourceEnd,     fps, useDropFrame),
            this._tc(clip.timelineStart, fps, useDropFrame),
            this._tc(clip.timelineEnd,   fps, useDropFrame),
          ));
        } else {
          // Straight cut
          lines.push(this._formatEvent(
            eventNum,
            reelId,
            'V',
            'C',
            this._tc(clip.sourceStart,   fps, useDropFrame),
            this._tc(clip.sourceEnd,     fps, useDropFrame),
            this._tc(clip.timelineStart, fps, useDropFrame),
            this._tc(clip.timelineEnd,   fps, useDropFrame),
          ));
        }

        // Clip name comment
        if (this.includeComments && (clip.name || asset?.name)) {
          lines.push(`* FROM CLIP NAME: ${clip.name || asset?.name}`);
        }

        // Unsupported features comment
        if (this.includeComments) {
          const nonCropEffects = (clip.effects ?? []).filter((e) => e.type !== 'crop');
          if (nonCropEffects.length > 0) {
            lines.push(`* EFFECTS: ${nonCropEffects.map((e) => e.type || e.videoForgeType).join(', ')} [not representable in EDL]`);
          }
          const crop = clip.crop ?? { l: 0, r: 0, t: 0, b: 0 };
          if (crop.l || crop.r || crop.t || crop.b) {
            const cropFx = (clip.effects ?? []).find((e) => e.type === 'crop');
            const alignment = cropFx ? (cropFx.getParam?.('alignment') ?? 'center') : 'center';
            lines.push(`* CROP: left=${crop.l}px right=${crop.r}px top=${crop.t}px bottom=${crop.b}px alignment=${alignment} [not representable in EDL]`);
          }
          if (clip.opacity !== 1) {
            lines.push(`* OPACITY: ${clip.opacity} [not representable in EDL]`);
          }
          if (clip.speed !== 1) {
            lines.push(`* SPEED: ${clip.speed}x [not representable in EDL]`);
          }
          if (clip.reverse) {
            lines.push('* REVERSE: true [not representable in EDL]');
          }
          if (clip.captionData !== null) {
            lines.push(`* CAPTION: "${(clip.captionData?.flattenToText() ?? '').slice(0, 60)}" [not representable in EDL]`);
          }
        }

        eventNum++;
        lines.push('');
      }

      // Secondary video tracks as comments
      if (this.includeComments && videoTracks.length > 1) {
        lines.push('* SECONDARY VIDEO TRACKS (not representable in CMX3600):');
        for (let t = 1; t < videoTracks.length; t++) {
          for (const clip of videoTracks[t].getSortedClips()) {
            const asset  = itr.getAsset(clip.assetId);
            lines.push(`* V${t + 1} ${this._reelId(asset, clip)} ${this._tc(clip.timelineStart, fps, useDropFrame)}-${this._tc(clip.timelineEnd, fps, useDropFrame)}`);
          }
        }
        lines.push('');
      }
    }

    // Audio events
    if (this.includeAudio) {
      const audioTracks = itr.getAudioTracks();
      for (let t = 0; t < audioTracks.length; t++) {
        const channelCode = t === 0 ? 'A' : `A${t + 1}`;
        for (const clip of audioTracks[t].getSortedClips()) {
          const asset  = itr.getAsset(clip.assetId);
          const reelId = this._reelId(asset, clip);

          lines.push(this._formatEvent(
            eventNum++,
            reelId,
            channelCode,
            'C',
            this._tc(clip.sourceStart,   fps, useDropFrame),
            this._tc(clip.sourceEnd,     fps, useDropFrame),
            this._tc(clip.timelineStart, fps, useDropFrame),
            this._tc(clip.timelineEnd,   fps, useDropFrame),
          ));

          if (this.includeComments && (clip.name || asset?.name)) {
            lines.push(`* FROM CLIP NAME: ${clip.name || asset?.name}`);
          }
          if (this.includeComments && clip.volume !== 1) {
            lines.push(`* VOLUME: ${clip.volume} [not representable in EDL]`);
          }
          if (clip.mute) {
            lines.push(`* MUTED [excluded from record out]`);
          }
          if (this.includeComments && clip.pan !== 0) {
            lines.push(`* PAN: ${clip.pan} [not representable in EDL]`);
          }
          if (this.includeComments && clip.speed !== 1) {
            lines.push(`* SPEED: ${clip.speed}x [not representable in EDL]`);
          }

          lines.push('');
        }
      }
    }

    // Caption tracks as comment annotations (not representable in CMX3600)
    if (this.includeComments) {
      const captionTracks = itr.getCaptionTracks();
      if (captionTracks.length > 0) {
        lines.push('* CAPTION TRACKS (not representable in CMX3600):');
        for (const track of captionTracks) {
          for (const clip of track.getSortedClips()) {
            const text = clip.captionData?.flattenToText() ?? '';
            lines.push(
              `* CAPTION: "${text.slice(0, 60)}" ` +
              `${this._tc(clip.timelineStart, fps, useDropFrame)}-` +
              `${this._tc(clip.timelineEnd, fps, useDropFrame)} ` +
              `[not representable in EDL]`,
            );
          }
        }
        lines.push('');
      }
    }

    return lines.join('\n');
  }

  // ─── Formatting helpers ───────────────────────────────────────────────────────

  /**
   * Format an edit event line.
   * @param {number} num   - Event number (001–999).
   * @param {string} reel  - Reel/tape name (max 8 chars for strict CMX3600).
   * @param {string} channel - 'V' | 'A' | 'AA' | 'VA' | 'B' etc.
   * @param {string} editType - 'C' (cut), 'D NNN' (dissolve), 'W NNN' (wipe), etc.
   * @param {string} srcIn  - Source in timecode.
   * @param {string} srcOut - Source out timecode.
   * @param {string} recIn  - Record in timecode.
   * @param {string} recOut - Record out timecode.
   * @returns {string}
   */
  _formatEvent(num, reel, channel, editType, srcIn, srcOut, recIn, recOut) {
    const evStr   = String(num).padStart(3, '0');
    const reelStr = String(reel).slice(0, 8).padEnd(8, ' ');
    const chanStr = String(channel).padEnd(4, ' ');
    const editStr = String(editType).padEnd(12, ' ');
    return `${evStr}  ${reelStr} ${chanStr} ${editStr} ${srcIn} ${srcOut} ${recIn} ${recOut}`;
  }

  /**
   * Convert seconds to a timecode string.
   * @param {number} seconds
   * @param {number} fps
   * @param {boolean} dropFrame
   * @returns {string}
   */
  _tc(seconds, fps, dropFrame) {
    const tc = new TimeCode(seconds ?? 0, fps);
    return dropFrame ? tc.toSmpteDf() : tc.toSmpteNdf();
  }

  /**
   * Derive a CMX3600 reel identifier from an asset or clip.
   * Reel IDs should be ≤ 8 characters in strict mode, but we use up to 32 for modern NLEs.
   * @param {object|undefined} asset
   * @param {object} clip
   * @returns {string}
   */
  _reelId(asset, clip) {
    if (asset?.path) {
      // Derive from filename without extension: "interview_01.mp4" → "INTERVW1"
      const filename = asset.path.replace(/\\/g, '/').split('/').pop() ?? '';
      const base = filename.replace(/\.[^.]+$/, '').replace(/[^a-zA-Z0-9_]/g, '_');
      return base.slice(0, 32) || 'BL';
    }
    if (clip.assetId) return clip.assetId.slice(0, 32);
    return 'BL'; // Black / missing reel
  }
}

export default EdlExporter;
